FROM python:3

RUN apt-get update
RUN apt-get install -y cmake python-mysqldb
#RUN ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#RUN brew update
#RUN brew install cmake